# ANOVA

In [1]:
import numpy as np
import pandas as pd
import random 
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.formula.api import ols
from statsmodels.multivariate.manova import MANOVA
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')
plt.rcParams["figure.figsize"] = (10,8)

In [2]:
sales = pd.read_csv('../regresion_lineal/ficheros/sales3.csv')
sales.head(2)

,area_code,state,market,market_size,profit,margin,sales,cogs,total_expenses,marketing,...,budget_cogs,budget_margin,budget_sales,productid,date,product_type,product,type,mes,año
0,203,Connecticut,East,Small Market,107.0,176.0,292.0,116.0,69.0,38.0,...,110.0,160.0,270.0,2,2010-04-01,Coffee,Columbian,Regular,4,2010
1,203,Connecticut,East,Small Market,75.0,135.0,225.0,90.0,60.0,29.0,...,80.0,130.0,210.0,2,2010-07-01,Coffee,Columbian,Regular,7,2010

In [3]:
lm = ols("profit~state+market+market_size+margin+sales+cogs+total_expenses+marketing+inventory+budget_profit+budget_cogs+budget_margin+budget_sales+date+product_type+product+type+mes+año",data= sales).fit()
sm.stats.anova_lm(lm)

                    df        sum_sq       mean_sq            F         PR(>F)
state             19.0  2.075144e+06  1.092181e+05   186.739401   0.000000e+00
market             3.0  2.502372e+04  8.341239e+03    14.261720   3.032354e-09
market_size        1.0  3.840934e+03  3.840934e+03     6.567169   1.042240e-02
date              23.0  1.002788e+05  4.359946e+03     7.454567   4.162011e-24
product_type       3.0  2.399941e+04  7.999802e+03    13.677936   7.075027e-09
product           12.0  1.560899e+05  1.300749e+04    22.240003   1.794324e-48
type               1.0  1.972897e+03  1.972897e+03     3.373228   6.633472e-02
margin             1.0  3.059914e+06  3.059914e+06  5231.793823   0.000000e+00
sales              1.0  3.071846e+05  3.071846e+05   525.219455  1.344904e-109
cogs               1.0  4.097318e+04  4.097318e+04    70.055298   7.770991e-17
total_expenses     1.0  1.408308e+05  1.408308e+05   240.790343   7.657019e-53
marketing          1.0  2.253637e+05  2.253637e+05   385.323282   3.867910e-82
inventory          1.0  1.238469e+05  1.238469e+05   211.751544   7.805861e-47
budget_profit      1.0  9.292416e+05  9.292416e+05  1588.802819  8.509695e-295
budget_cogs        1.0  3.040564e+04  3.040564e+04    51.987091   6.597613e-13
budget_margin      1.0  1.585780e+05  1.585780e+05   271.134178   4.475163e-59
budget_sales       1.0  2.238420e+04  2.238420e+04    38.272154   6.743164e-10
mes                1.0  3.341572e+02  3.341572e+02     0.571337   4.497708e-01
año                1.0  1.662521e+01  1.662521e+01     0.028426   8.661205e-01
Residual        4183.0  2.446507e+06  5.848691e+02          NaN            NaN

In [4]:
#realizamos el summary
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                 profit   R-squared:                       0.752
Model:                            OLS   Adj. R-squared:                  0.748
Method:                 Least Squares   F-statistic:                     198.3
Date:                Tue, 14 Feb 2023   Prob (F-statistic):               0.00
Time:                        16:59:32   Log-Likelihood:                -19528.
No. Observations:                4248   AIC:                         3.919e+04
Df Residuals:                    4183   BIC:                         3.960e+04
Df Model:                          64
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.0249      0.004     -6.231      0.000      -0.033      -0.017
state[T.Colorado]               -3.1632      1.473     -2.147      0.032      -6.051      -0.275
state[T.Connecticut]            -0.4273      1.725     -0.248      0.804      -3.808       2.954
state[T.Florida]                -2.3542      1.576     -1.493      0.135      -5.445       0.737
state[T.Illinois]                9.5878      1.617      5.928      0.000       6.417      12.759
state[T.Iowa]                    1.8290      1.589      1.151      0.250      -1.286       4.944
state[T.Louisiana]               0.9318      1.634      0.570      0.568      -2.271       4.134
state[T.Massachusetts]          -7.5588      1.834     -4.122      0.000     -11.154      -3.963
state[T.Missouri]               -2.9465      1.542     -1.911      0.056      -5.970       0.077
state[T.Nevada]                  1.4923      1.683      0.887      0.375      -1.807       4.792
state[T.New Hampshire]           1.3857      1.737      0.798      0.425      -2.020       4.792
state[T.New Mexico]             -5.0236      1.662     -3.023      0.003      -8.282      -1.765
state[T.New York]                7.3586      1.704      4.318      0.000       4.018      10.699
state[T.Ohio]                   -5.1123      1.603     -3.190      0.001      -8.255      -1.970
state[T.Oklahoma]                0.5022      1.639      0.307      0.759      -2.710       3.715
state[T.Oregon]                  1.3827      1.583      0.874      0.382      -1.721       4.486
state[T.Texas]                   5.6288      1.643      3.426      0.001       2.408       8.850
state[T.Utah]                   -2.8577      1.544     -1.851      0.064      -5.884       0.169
state[T.Washington]             -2.3645      1.642     -1.440      0.150      -5.584       0.855
state[T.Wisconsin]              -0.8553      1.520     -0.563      0.574      -3.835       2.124
market[T.East]                  -1.5960      0.821     -1.945      0.052      -3.205       0.013
market[T.South]                  2.0392      0.834      2.446      0.014       0.405       3.674
market[T.West]                   0.1924      1.097      0.175      0.861      -1.958       2.343
market_size[T.Small Market]     -6.9511      0.958     -7.254      0.000      -8.830      -5.073
date[T.2010-02-01]              -0.0402      2.410     -0.017      0.987      -4.765       4.685
date[T.2010-03-01]              -2.6909      2.260     -1.191      0.234      -7.122       1.740
date[T.2010-04-01]              -4.1065      2.122     -1.935      0.053      -8.267       0.054
date[T.2010-05-01]              -1.0545      2.005     -0.526      0.599      -4.985       2.876
date[T.2010-06-01]              -1.6069      1.905     -0.844      0.399      -5.341       2.127
date[T.2010-07-01]              -4.9523      1.830     -2.707      0.007      -8.539      -1.365
date[T.2010-08-01]              -3.6912      1.782     -2.071      0.038      -7.185      -0.197
date[T.2010-09-01]              -4.7010      1.765     -2.664      0.008      -8.160      -1.242
date[T.2010-10-01]             -14.0964      1.791     -7.871      0.000     -17.607     -10.585
date[T.2010-11-01]               0.5718      1.815      0.315      0.753      -2.987       4.131
date[T.2010-12-01]              -2.0769      1.882     -1.104      0.270      -5.766       1.613
date[T.2011-01-01]               4.8729      2.586      1.884      0.060      -0.198       9.943
date[T.2011-02-01]               5.9973      2.416      2.483      0.013       1.261      10.733
date[T.2011-03-01]               4.8398      2.266      2.136      0.033       0.397       9.282
date[T.2011-04-01]               3.7854      2.127      1.780      0.075      -0.384       7.955
date[T.2011-05-01]               4.7883      2.004      2.389      0.017       0.859       8.718
date[T.2011-06-01]               4.8197      1.906      2.529      0.011       1.083       8.556
date[T.2011-07-01]               1.2788      1.832      0.698      0.485      -2.312       4.870
date[T.2011-08-01]               1.9926      1.784      1.117      0.264      -1.505       5.491
date[T.2011-09-01]               5.5421      1.763      3.144      0.002       2.086       8.998
date[T.2011-10-01]              -3.9611      1.789     -2.215      0.027      -7.468      -0.455
date[T.2011-11-01]              10.1802      1.815      5.609      0.000       6.622      13.738
date[T.2011-12-01]               5.8923      1.882      3.131      0.002       2.202       9.582
product_type[T.Espresso]         2.9331      1.516      1.935      0.053      -0.039       5.905
product_type[T.Herbal Tea]      -0.1015      0.897     -0.113      0.910      -1.859       1.656
product_type[T.Tea]              4.7779      1.520      3.144      0.002       1.799       7.757
product[T.Caffe Latte]          -0.7042      1.691     -0.416      0.677      -4.020       2.612
product[T.Caffe Mocha]          -4.4506      1.281     -3.474      0.001      -6.962      -1.939
product[T.Chamomile]             2.3985      1.116      2.150      0.032       0.211       4.586
product[T.Columbian]             3.0651      2.156      1.422      0.155      -1.162       7.292
product[T.Darjeeling]            0.7626      1.163      0.656      0.512      -1.517       3.042
product[T.Decaf Espresso]        3.7456      1.097      3.415      0.001       1.596       5.896
product[T.Decaf Irish Cream]    -4.0998      1.277     -3.209      0.001      -6.604      -1.595
product[T.Earl Grey]             1.9899      1.287      1.547      0.122      -0.533       4.512
product[T.Green Tea]             2.0253      1.306      1.551      0.121      -0.535       4.586
product[T.Lemon]                 0.0769      1.050      0.073      0.942      -1.982       2.136
product[T.Mint]                 -2.5769      1.457     -1.768      0.077      -5.434       0.280
product[T.Regular Espresso]      4.3422      2.591      1.676      0.094      -0.737       9.421
type[T.Regular]                  0.4308      1.138      0.379      0.705      -1.800       2.662
margin                           0.2008      0.019     10.603      0.000       0.164       0.238
sales                            0.3188      0.017     18.253      0.000       0.285       0.353
cogs                            -0.2631      0.034     -7.698      0.000      -0.330      -0.196
total_expenses                  -0.3068      0.037     -8.211      0.000      -0.380      -0.234
marketing                        0.4168      0.051      8.219      0.000       0.317       0.516
inventory                        0.0108      0.002      7.029      0.000       0.008       0.014
budget_profit                    0.8413      0.020     42.971      0.000       0.803       0.880
budget_cogs                      0.0415      0.024      1.761      0.078      -0.005       0.088
budget_margin                   -0.2946      0.022    -13.508      0.000      -0.337      -0.252
budget_sales                    -0.0899      0.015     -6.192      0.000      -0.118      -0.061
mes                              0.0362      0.244      0.148      0.882      -0.443       0.515
año                             -0.0043      0.001     -3.152      0.002      -0.007      -0.002
==============================================================================
Omnibus:                     1442.275   Durbin-Watson:                   1.588
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            30624.289
Skew:                           1.100   Prob(JB):                         0.00
Kurtosis:                      15.968   Cond. No.                     6.41e+18
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.72e-28. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

Interpretación:
- Vemos que nuestro r_sq y el ajustado tienen un valor de 0.75, con lo cual nuestras variables predictoras representan el 75% de los beneficios de los supermercados.

- Según estado (state) el coeficiente varía de uno a otro, los valores positivos nos indican el aumento del beneficio en función del estado donde se vende el producto, por ejemplo en  Illinois o Iowa entre otros. Sin embargo en otros estados como en Ohio , Utha y otros más, este coeficiente es negativo. Este comportamiento se repite en la mayoría de las variables. Solamente en aquellas referentes al beneficio, ventas y margen es puramente positiva y en gastos (en general) es puramente negativa. 

- Sobre el valor de p-value, descartamos las variables *budget_cogs* y *type* ya que su valor es mayor a 0.05 por lo tanto no son significativas.
- Sobre el valor del error estándar, apreciamos una clara diferencia entre los resultados de las variables categóricas (más alto) que de las variables numéricas (cerca de 0). Cuanto menor sea , más precisa es la estimación. 
- Por lo tanto, decidimos eliminar las columnas *budget_cogs'*, *mes* y *type* y *date*. Nos quedamos con *año* por ser relevante para el modelo. Eliminamos también las columnas *area_code* y *productid* por tener información redundante para el modelo.

In [5]:
sales = sales.drop(columns=["budget_cogs",'type','productid','area_code','mes','date'],axis = 1)

In [6]:
sales.head(2)

,state,market,market_size,profit,margin,sales,cogs,total_expenses,marketing,inventory,budget_profit,budget_margin,budget_sales,product_type,product,año
0,Connecticut,East,Small Market,107.0,176.0,292.0,116.0,69.0,38.0,962.0,110.0,160.0,270.0,Coffee,Columbian,2010
1,Connecticut,East,Small Market,75.0,135.0,225.0,90.0,60.0,29.0,1148.0,90.0,130.0,210.0,Coffee,Columbian,2010

In [7]:
sales.to_csv('ficheros/sales4.csv',index = False)